version: '3.8'

# Define services
services:
  # Database Service (MySQL)
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network  # Use a single bridge network

  # Backend Service (Spring Boot)
  springboot-app:
    image: pramod858/backend-ecommerce:latest
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      ANGULAR_URL: http://localhost # Use this for development
    depends_on:
      - mysql
    networks:
      - app-network  # Use a single bridge network

  # Frontend Service (Angular)
  angular-app:
    image: pramod858/frontend-ecommerce:latest
    container_name: angular_app
    ports:
      - "80:80"
    depends_on:
      - springboot-app
    networks:
      - app-network  # Use a single bridge network

# Define Networks
networks:
  app-network:
    driver: bridge  # Explicitly define a bridge network

# Define Volumes
volumes:
  mysql_data:
