---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: pramod-app
  labels:
    app: mysql-db
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: mydb
  MYSQL_USER: user
  MYSQL_PASSWORD: userpass