namespace: pramod-app

mysql:
  image: mysql:8.0
  rootPassword: rootpass
  database: mydb
  user: user
  password: userpass

angular:
  image: pramod858/frontend-ecommerce:latest
  replicas: 2
  host: app.pramodpro.xyz

springboot:
  image: pramod858/backend-ecommerce:latest
  host: api.pramodpro.xyz
  angularUrl: https://app.pramodpro.xyz

alb:
  certificateArn: "<your-acm-cert-arn>"
