apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.angular.replicas }}
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-container
          image: {{ .Values.angular.image }}
          ports:
            - containerPort: 80
