apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: {{ .Values.angular.port }}
      targetPort: {{ .Values.angular.port }}
  type: {{ .Values.serviceType }}