apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: mysql-db
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysqlRootPassword }}
  MYSQL_DATABASE: {{ .Values.mysqlDatabase }}
  MYSQL_USER: {{ .Values.mysqlUser }}
  MYSQL_PASSWORD: {{ .Values.mysqlPassword }}