apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: springboot-app
