apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.angular.port }}
      targetPort: {{ .Values.springboot.port }}
  selector:
    app: springboot-app