name: Java CI with Maven

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Check out the repository

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Compile with Maven
      run: mvn -B compile --file pom.xml
      working-directory: ./Back-End-Ecommerce

    - name: Build with Maven
      run: mvn -B clean package -DskipTests
      working-directory: ./Back-End-Ecommerce

    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: ./Back-End-Ecommerce/target/*.jar

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file docker/backend/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/backend-ecommerce:latest
      working-directory: ./Back-End-Ecommerce

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend-ecommerce:latest
